### ISSUE TITLE
Need to make screen height and width with hooks for the universal imgui android 

### ISSUE THREAD

**Issue by biteyt** [springmusk026/ImGui-Touch-Universal-Android-#4]
Theres many types of screen width like the noob java API, define 1920x1080 with float and with java, theres one more (the best for il2cpp) with BNM that gets the UnityEngine screen class, get_width and get_height methods, but we need the universal one right, because in non-il2cpp games the BNM doesn't work out right, you need to get the screen size universally and use it in ImGui_ImplAndroid_NewFrame(int x, int y,); for it to work correctly in every game. ❤️

**Comment by ozMod** [comment]
you could use eglQuerySurface for that, or hook ANativeWindow_getWidth

**Comment by springmusk026** [comment]
https://github.com/springmusk026/ImGui-Unity-With-Layout

**Comment by springmusk026** [comment]
int32_t (*old_ANativeWindow_getWidth)(ANativeWindow* window);
int32_t new_ANativeWindow_getWidth(ANativeWindow* window){
    int32_t returnValue = old_ANativeWindow_getWidth(window);
    LOGI("Recieved Display Width: %d", returnValue);
    glWidth = (int)returnValue;
    width = returnValue;
    return returnValue;
}

int32_t (*old_ANativeWindow_getHeight)(ANativeWindow* window);
int32_t new_ANativeWindow_getHeight(ANativeWindow* window) {
    int32_t returnValue = old_ANativeWindow_getHeight(window);
    LOGI("Recieved Display Height: %d", returnValue);
    glHeight = returnValue;
    height = returnValue;
    return returnValue;
}


use like this 

or


 eglQuerySurface(dpy, surface, EGL_WIDTH, &glWidth);
    eglQuerySurface(dpy, surface, EGL_HEIGHT, &glHeight);

**Comment by biteyt** [comment]
Sir I already got it, I use the eglQuerySurface with impl android
